# Generated by Django 5.1.7 on 2025-03-17 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albom',
            options={'verbose_name_plural': 'Albomlar'},
        ),
        migrations.AlterModelOptions(
            name='qoshiq',
            options={'verbose_name_plural': "Qo'shiqlar"},
        ),
        migrations.AlterModelOptions(
            name='qoshiqchi',
            options={'verbose_name_plural': "Qo'shiqchilar"},
        ),
    ]
